# Generated by Django 6.0.2 on 2026-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
    ]
